spring.application.name=SalesSavvy
server.port = 9090
spring.datasource.url=jdbc:mysql://localhost:3306/salessavvy
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

jwt.secret=your-very-long-secure-secret-key-for-production-12345678901234567890
jwt.expiration=3600000

spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

razorpay.key_id=rzp_test_TTgAnEZaXxYfXZ
razorpay.key_secret=U65QUQT92Cip7SatWy1vDzMe